workflows:
  dev-workflow:
    name: Dev
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: 3.24.3 # Or a specific version
      xcode: 15.4 # Or a specific version
      cocoapods: 1.15.2

    scripts:
      # Set up environment
      - name: Set up Flutter
        script: flutter pub get

      # Run Tests (Add this section)
      - name: Run Flutter Tests
        script: flutter test --coverage

      # Android build
      - name: Build Android APK
        script: |
          flutter build apk --debug

      # Install CocoaPods dependencies
      - name: Install CocoaPods
        script: |
          cd ios
          pod install

      # iOS build
      - name: Build Debug for iOS
        script: flutter build ios --no-codesign

      # Zip the iOS .app bundle
      - name: Zip the iOS .apk
        script: |
          cd build/ios/iphoneos
          zip -r Runner.app.zip Runner.app

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk # APK for Android
      - build/ios/iphoneos/Runner.app.zip
      - coverage/ #include coverage reports

    publishing:
      email:
        # Replace with your email address
        recipients:
          - fandiaspraja@gmail.com
        # notify:
        #   success: true
        #   failure: false
