workflows:
  dev-workflow:
    name: Dev
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable # Or a specific version
      xcode: latest # Or a specific version

    scripts:
      # Set up environment
      - name: Set up Flutter
        script: flutter pub get

      # Run Tests (Add this section)
      - name: Run Flutter Tests
        script: flutter test --coverage

      # Android build
      - name: Build Android APK
        script: |
          flutter build apk --debug

      # iOS build
      - name: Build iOS IPA
        script: |
          flutter build ios --no-codesign

      # Archive the iOS .app bundle into a zip
      - name: Zip the iOS .app bundle
        script: |
          cd build/ios/iphoneos
          zip -r Runner.app.zip Runner.app

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk # APK for Android
      - build/ios/iphoneos/Runner.app.zip
      - coverage/ #include coverage reports

    publishing:
      email:
        # Replace with your email address
        recipients:
          - fandiaspraja@gmail.com
        # notify:
        #   success: true
        #   failure: false
