// Mocks generated by Mockito 5.4.4 from annotations
// in ditonton/test/presentation/pages/top_rated_tvshow_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:ditonton/common/state_enum.dart' as _i5;
import 'package:ditonton/domain/entities/tvshow.dart' as _i4;
import 'package:ditonton/domain/usecases/get_top_rated_tvshows.dart' as _i2;
import 'package:ditonton/presentation/provider/top_rated_tvshow_notifier.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTopRatedTvshows_0 extends _i1.SmartFake
    implements _i2.GetTopRatedTvshows {
  _FakeGetTopRatedTvshows_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TopRatedTvshowNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTvshowNotifier extends _i1.Mock
    implements _i3.TopRatedTvshowNotifier {
  MockTopRatedTvshowNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTopRatedTvshows get getTopRatedTvshows => (super.noSuchMethod(
        Invocation.getter(#getTopRatedTvshows),
        returnValue: _FakeGetTopRatedTvshows_0(
          this,
          Invocation.getter(#getTopRatedTvshows),
        ),
      ) as _i2.GetTopRatedTvshows);

  @override
  List<_i4.Tvshow> get topRatedTvshows => (super.noSuchMethod(
        Invocation.getter(#topRatedTvshows),
        returnValue: <_i4.Tvshow>[],
      ) as List<_i4.Tvshow>);

  @override
  _i5.RequestState get topRatedTvshowsState => (super.noSuchMethod(
        Invocation.getter(#topRatedTvshowsState),
        returnValue: _i5.RequestState.Empty,
      ) as _i5.RequestState);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> fetchTopRatedTvshows() => (super.noSuchMethod(
        Invocation.method(
          #fetchTopRatedTvshows,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
